// biome-ignore-all lint: generated bindings
// This file is generated by `pnpm --filter jobnest api:generate`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createCompany: (input: CreateCompanyInput) => __TAURI_INVOKE<Company>("create_company", { input }),
	createRole: (input: CreateRoleInput) => __TAURI_INVOKE<Role>("create_role", { input }),
	createApplication: (input: CreateApplicationInput) => __TAURI_INVOKE<Application>("create_application", { input }),
	createTrackedApplication: (input: CreateTrackedApplicationInput) => __TAURI_INVOKE<ApplicationListItem>("create_tracked_application", { input }),
	updateApplicationStatus: (input: UpdateApplicationStatusInput) => __TAURI_INVOKE<Application>("update_application_status", { input }),
	updateTrackedApplication: (input: UpdateTrackedApplicationInput) => __TAURI_INVOKE<ApplicationListItem>("update_tracked_application", { input }),
	deleteTrackedApplication: (applicationId: string) => __TAURI_INVOKE<null>("delete_tracked_application", { applicationId }),
	createContact: (input: CreateContactInput) => __TAURI_INVOKE<Contact>("create_contact", { input }),
	createNote: (input: CreateNoteInput) => __TAURI_INVOKE<Note>("create_note", { input }),
	search: (query: string, filters: {
	entityTypes: string[] | null,
	onlyActiveApplications: boolean | null,
	statuses: string[] | null,
} | null, limit: number | null, offset: number | null) => __TAURI_INVOKE<SearchResult[]>("search", { query, filters, limit, offset }),
	reindexSearch: () => __TAURI_INVOKE<null>("reindex_search"),
	listApplications: () => __TAURI_INVOKE<ApplicationListItem[]>("list_applications"),
	getAppSettings: () => __TAURI_INVOKE<AppSettings>("get_app_settings"),
	updateAppSettings: (input: UpdateAppSettingsInput) => __TAURI_INVOKE<AppSettings>("update_app_settings", { input }),
	resetAppData: () => __TAURI_INVOKE<AppSettings>("reset_app_data"),
	exportAppData: () => __TAURI_INVOKE<ExportData>("export_app_data"),
	importAppData: (input: ImportDataInput) => __TAURI_INVOKE<ExportData>("import_app_data", { input }),
};

/* Types */
export type AppSettings = {
	preferredCurrency: string,
	updatedAt: string,
};

export type Application = {
	id: string,
	roleId: string,
	status: string,
	appliedAt: string | null,
	firstResponseAt: string | null,
	deadlineAt: string | null,
	salaryExpectation: string | null,
	salaryOffer: string | null,
	lastActivityAt: string,
	priority: number,
	archivedAt: string | null,
	createdAt: string,
	updatedAt: string,
};

export type ApplicationListItem = {
	id: string,
	companyName: string,
	roleTitle: string,
	jobPostUrl: string | null,
	salaryExpectation: string | null,
	salaryOffer: string | null,
	status: string,
	appliedAt: string | null,
	firstResponseAt: string | null,
	notes: string | null,
	updatedAt: string,
	archivedAt: string | null,
};

export type Attachment = {
	id: string,
	applicationId: string,
	kind: string,
	fileName: string,
	filePath: string,
	mimeType: string | null,
	createdAt: string,
};

export type Company = {
	id: string,
	name: string,
	website: string | null,
	location: string | null,
	industry: string | null,
	createdAt: string,
	updatedAt: string,
};

export type Contact = {
	id: string,
	companyId: string,
	name: string,
	title: string | null,
	email: string | null,
	linkedinUrl: string | null,
	notes: string | null,
	createdAt: string,
	updatedAt: string,
};

export type CreateApplicationInput = {
	roleId: string,
	status: string,
	appliedAt: string | null,
	firstResponseAt: string | null,
	deadlineAt: string | null,
	salaryExpectation: string | null,
	salaryOffer: string | null,
	priority: number | null,
};

export type CreateCompanyInput = {
	name: string,
	website: string | null,
	location: string | null,
	industry: string | null,
};

export type CreateContactInput = {
	companyId: string,
	name: string,
	title: string | null,
	email: string | null,
	linkedinUrl: string | null,
	notes: string | null,
};

export type CreateNoteInput = {
	applicationId: string,
	body: string,
	kind: string | null,
};

export type CreateRoleInput = {
	companyId: string,
	title: string,
	jobBoard: string | null,
	sourceUrl: string | null,
	employmentType: string | null,
	locationText: string | null,
	salaryText: string | null,
	description: string | null,
};

export type CreateTrackedApplicationInput = {
	jobPostUrl: string,
	companyName: string,
	roleTitle: string,
	salaryExpectation: string | null,
	salaryOffer: string | null,
	status: string | null,
	appliedAt: string | null,
	firstResponseAt: string | null,
	notes: string | null,
};

export type ExportData = {
	companies: Company[],
	roles: Role[],
	applications: Application[],
	contacts: Contact[],
	notes: Note[],
	tasks: Task[],
	attachments: Attachment[],
	stage_events: StageEvent[],
	app_settings: AppSettings,
	export_version: string,
	exported_at: string,
};

export type ImportDataInput = {
	companies: Company[],
	roles: Role[],
	applications: Application[],
	contacts: Contact[],
	notes: Note[],
	tasks: Task[],
	attachments: Attachment[],
	stage_events: StageEvent[],
	app_settings: AppSettings | null,
};

export type Note = {
	id: string,
	applicationId: string,
	body: string,
	kind: string,
	createdAt: string,
	updatedAt: string,
};

export type Role = {
	id: string,
	companyId: string,
	title: string,
	jobBoard: string | null,
	sourceUrl: string | null,
	employmentType: string | null,
	locationText: string | null,
	salaryText: string | null,
	description: string | null,
	createdAt: string,
	updatedAt: string,
};

export type SearchFilters = {
	entityTypes: string[] | null,
	onlyActiveApplications: boolean | null,
	statuses: string[] | null,
};

export type SearchResult = {
	entityType: string,
	entityId: string,
	title: string,
	subtitle: string,
	snippet: string,
	score: number,
};

export type StageEvent = {
	id: string,
	applicationId: string,
	fromStatus: string | null,
	toStatus: string,
	changedAt: string,
	source: string,
};

export type Task = {
	id: string,
	applicationId: string,
	title: string,
	dueAt: string | null,
	completedAt: string | null,
	kind: string,
	createdAt: string,
	updatedAt: string,
};

export type UpdateAppSettingsInput = {
	preferredCurrency: string,
};

export type UpdateApplicationStatusInput = {
	applicationId: string,
	status: string,
	source: string | null,
};

export type UpdateTrackedApplicationInput = {
	applicationId: string,
	jobPostUrl: string,
	companyName: string,
	roleTitle: string,
	salaryExpectation: string | null,
	salaryOffer: string | null,
	status: string,
	notes: string | null,
};

